# Workflow for building and deploying a Jekyll site via ssh
name: Deploy Jekyll via ssh

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ruby/setup-ruby@ee2113536afb7f793eed4ce60e8d3b26db912da4 # v1.127.0
        with:
          ruby-version: '3.0' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          cache-version: 0 # Increment this number if you need to re-download cached gems
      - name: Build with Jekyll
        # Outputs to the './_site' directory by default
        run: bundle exec jekyll build --baseurl "${{ vars.BASE_URL }}"
        env:
          JEKYLL_ENV: production
      - name: Upload artifact
        # Automatically uploads an artifact from the './_site' directory by default
        uses: actions/upload-pages-artifact@v1
      - name: Deploy to server over ssh
        # Use rsync over ssh to upload to server
        uses: easingthemes/ssh-deploy@v4
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }} 
          ARGS: "-rlgoDzvc -i" # default "-rlgoDzvc -i"
          SOURCE: "./_site/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }} # "www.mat.uniroma2.it"
          REMOTE_USER: ${{ secrets.REMOTE_USER }} # "butterle"
          TARGET: ${{ secrets.REMOTE_TARGET }}  # "~/public_html/"
          EXCLUDE: ""

